# Use Python 3.12.3 as the base image
FROM python:3.12.3-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Expose the port where the Streamlit app will run (default is 8501)
EXPOSE 8501

# Set the Streamlit config to prevent asking to set browser in container
ENV STREAMLIT_SERVER_HEADLESS=True

# Run the app
CMD ["streamlit", "run", "app.py"]
