FROM python:3.9

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app files
COPY . .

# Expose the port that Streamlit runs on
EXPOSE 8501

# Run the app
CMD ["streamlit", "run", "app.py"]
