name: Streamlit GPT App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ensure environment variables are set for API keys (mocked in tests)
    - name: Mock API Keys (For Testing)
      run: |
        echo "HUGGINGFACEHUB_API_TOKEN=fake-api-key" >> $GITHUB_ENV
        echo "GOOGLE_API_KEY=fake-google-api-key" >> $GITHUB_ENV

    # Run the tests
    - name: Run tests
      run: |
        pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    
    # Login to DockerHub using secrets
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile  # Ensure the file is named Dockerfile (case-sensitive)
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/gpt-streamlit-app:latest
